"""
This module defines the data channels available in the simulation.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Optional

from simulation.solution import SolutionNode


class Channel(ABC):
    """
    An abstract class representing a data channel.
    """

    _REGISTRY: dict[str, type[Channel]] = {}
    name: str
    unit: Optional[str] = None

    def __init_subclass__(
        cls: type[Channel], name: str, unit: Optional[str] = None
    ) -> None:
        super().__init_subclass__()
        cls._REGISTRY[name] = cls
        cls.name = name
        cls.unit = unit

    @classmethod
    def get_channel(cls, channel_name: str) -> Channel:
        """
        Get a data channel from its name.

        Args:
            channel_name (str): The name of the data channel.

        Raises:
            KeyError: If no data channel with the given name exists.

        Returns:
            channel (type[Channel]): A data channel object.
        """
        try:
            return cls._REGISTRY[channel_name]()
        except KeyError:
            error_message = (
                f"Data channel '{channel_name}' not found. "
                f"Available channels: {list(cls._REGISTRY.keys())}"
            )
            raise KeyError(error_message)

    @classmethod
    def list_channels(cls) -> list[str]:
        """
        Get a list of available data channels.

        Returns:
            channels (list[str]): Available data channel names.
        """
        return list(cls._REGISTRY.keys())

    @staticmethod
    @abstractmethod
    def get_value(solution_node: SolutionNode) -> float:
        """
        Get the value of a data channel.

        Args:
            solution_node (SolutionNode): A solution node.

        Returns:
            value (float): The value of the corresponding data channel.
        """
        ...


class CentripetalForce(Channel, name="Centripetal Force", unit="N"):
    """Centripetal force acting on the vehicle."""

    @staticmethod
    def get_value(solution_node: SolutionNode) -> float:
        return solution_node.vehicle_state.centripetal_force


class Downforce(Channel, name="Downforce", unit="N"):
    """Aerodynamic downforce."""

    @staticmethod
    def get_value(solution_node: SolutionNode) -> float:
        return solution_node.vehicle_state.downforce


class Drag(Channel, name="Drag", unit="N"):
    """Aerodynamic drag force."""

    @staticmethod
    def get_value(solution_node: SolutionNode) -> float:
        return solution_node.vehicle_state.drag


class ResistiveFx(Channel, name="Resistive Force", unit="N"):
    """Total resistive force acting on the vehicle."""

    @staticmethod
    def get_value(solution_node: SolutionNode) -> float:
        return solution_node.vehicle_state.resistive_fx


class RequiredFy(Channel, name="Required Fy", unit="N"):
    """Lateral force required to navigate the track."""

    @staticmethod
    def get_value(solution_node: SolutionNode) -> float:
        return solution_node.vehicle_state.required_fy


class NormalForce(Channel, name="Normal Force", unit="N"):
    """Total normal force exerted by the vehicle."""

    @staticmethod
    def get_value(solution_node: SolutionNode) -> float:
        return solution_node.vehicle_state.normal_force


class TotalLateralTraction(Channel, name="Total Lateral Traction", unit="N"):
    """Total lateral traction force generated by the tyres."""

    @staticmethod
    def get_value(solution_node: SolutionNode) -> float:
        return solution_node.vehicle_state.total_lateral_traction


class MotorSpeed(Channel, name="Motor Speed", unit="rad/s"):
    """Rotational velocity of the motor."""

    @staticmethod
    def get_value(solution_node: SolutionNode) -> float:
        return solution_node.vehicle_state.motor_speed


class MotorTorque(Channel, name="Motor Torque", unit="Nm"):
    """Torque generated by the motor."""

    @staticmethod
    def get_value(solution_node: SolutionNode) -> float:
        return solution_node.vehicle_state.motor_torque


class MotorForce(Channel, name="Motor Force", unit="N"):
    """Equivalent motor force measured at the wheels."""

    @staticmethod
    def get_value(solution_node: SolutionNode) -> float:
        return solution_node.vehicle_state.motor_force


class Curvature(Channel, name="Curvature", unit="1/m"):
    """Curvature of the track."""

    @staticmethod
    def get_value(solution_node: SolutionNode) -> float:
        return solution_node.track_node.curvature


class CornerRadius(Channel, name="Corner Radius", unit="m"):
    """Radius of the track."""

    @staticmethod
    def get_value(solution_node: SolutionNode) -> float:
        return solution_node.track_node.radius


class Velocity(Channel, name="Velocity", unit="m/s"):
    """Velocity of the vehicle."""

    @staticmethod
    def get_value(solution_node: SolutionNode) -> float:
        return solution_node.velocity
