"""
This module contains definitions of data channels.
"""

from usmlap.simulation import Solution
from usmlap.simulation.channels import functions as fcn
from usmlap.utils.units import Unit

from .channel import Channel, Data, Lap


class CentripetalForce(
    Channel[Data], name="Centripetal Force", unit=Unit.NEWTON
):
    """Centripetal force acting on the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [
            node.calculated_vehicle_state.centripetal_force for node in solution
        ]


class Downforce(Channel[Data], name="Downforce", unit=Unit.NEWTON):
    """Aerodynamic downforce."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.calculated_vehicle_state.downforce for node in solution]


class Drag(Channel[Data], name="Drag", unit=Unit.NEWTON):
    """Aerodynamic drag force."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.calculated_vehicle_state.drag for node in solution]


class DragPower(Channel[Data], name="Drag Power", unit=Unit.KILOWATT):
    """Aerodynamic drag power."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return fcn.product(Drag(), Velocity())(solution)


class DragEnergy(Channel[Data], name="Drag Energy", unit=Unit.JOULE):
    """Aerodynamic drag energy."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return fcn.integral(Drag(), Distance())(solution)


class ResistiveFx(Channel[Data], name="Resistive Force", unit=Unit.NEWTON):
    """Total resistive force acting on the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.calculated_vehicle_state.resistive_fx for node in solution]


class RequiredFy(Channel[Data], name="Required Fy", unit=Unit.NEWTON):
    """Lateral force required to navigate the track."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.calculated_vehicle_state.required_fy for node in solution]


class NormalForce(Channel[Data], name="Normal Force", unit=Unit.NEWTON):
    """Total normal force exerted by the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.calculated_vehicle_state.normal_force for node in solution]


class TyreLoadFL(Channel[Data], name="Tyre Load FL", unit=Unit.NEWTON):
    """Normal load on the front left tyre."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [
            node.calculated_vehicle_state.normal_loads.front_left
            for node in solution
        ]


class TyreLoadFR(Channel[Data], name="Tyre Load FR", unit=Unit.NEWTON):
    """Normal load on the front right tyre."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [
            node.calculated_vehicle_state.normal_loads.front_right
            for node in solution
        ]


class TyreLoadRL(Channel[Data], name="Tyre Load RL", unit=Unit.NEWTON):
    """Normal load on the rear left tyre."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [
            node.calculated_vehicle_state.normal_loads.rear_left
            for node in solution
        ]


class TyreLoadRR(Channel[Data], name="Tyre Load RR", unit=Unit.NEWTON):
    """Normal load on the rear right tyre."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [
            node.calculated_vehicle_state.normal_loads.rear_right
            for node in solution
        ]


class LongLT(
    Channel[Data], name="Longitudinal Load Transfer", unit=Unit.NEWTON
):
    """Longitudinal load transfer."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.calculated_vehicle_state.long_lt for node in solution]


class LatLT(Channel[Data], name="Lateral Load Transfer", unit=Unit.NEWTON):
    """Lateral load transfer."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.calculated_vehicle_state.lat_lt for node in solution]


class MotorSpeed(
    Channel[Data], name="Motor Speed", unit=Unit.RADIANS_PER_SECOND
):
    """Rotational velocity of the motor."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.calculated_vehicle_state.motor_speed for node in solution]


class MotorTorque(Channel[Data], name="Motor Torque", unit=Unit.NEWTON_METER):
    """Torque generated by the motor."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.calculated_vehicle_state.motor_torque for node in solution]


class MotorPower(Channel[Data], name="Motor Power", unit=Unit.KILOWATT):
    """Power output by the motor."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return fcn.product(MotorTorque(), MotorSpeed())(solution)


class MotorEnergy(Channel[Data], name="Motor Energy", unit=Unit.KILOWATT_HOUR):
    """Energy output by the motor."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return fcn.integral(MotorPower(), SegmentTime())(solution)


class MotorForce(Channel[Data], name="Motor Force", unit=Unit.NEWTON):
    """Equivalent motor force measured at the wheels."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.calculated_vehicle_state.motor_force for node in solution]


class Curvature(Channel[Data], name="Curvature", unit=Unit.PER_METER):
    """Curvature of the track."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.track_node.curvature for node in solution]


class CornerRadius(Channel[Data], name="Corner Radius", unit=Unit.METER):
    """Radius of the track."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.track_node.radius for node in solution]


class Distance(Channel[Data], name="Distance", unit=Unit.METER):
    """Length of the track segment."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.track_node.length for node in solution]


class Position(Channel[Data], name="Position", unit=Unit.METER):
    """Position of the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.track_node.position for node in solution]


class Velocity(Channel[Data], name="Velocity", unit=Unit.KILOMETER_PER_HOUR):
    """Velocity of the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.average_velocity for node in solution]


class MaximumVelocity(
    Channel[Data], name="Maximum Velocity", unit=Unit.KILOMETER_PER_HOUR
):
    """Maximum, velocity of the vehicle, limited by lateral grip."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.maximum_velocity for node in solution]


class SegmentTime(Channel[Data], name="Segment Time", unit=Unit.SECOND):
    """Time taken to traverse the track segment."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.time for node in solution]


class Time(Channel[Data], name="Time", unit=Unit.SECOND):
    """Cumulative time for the simulation."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return fcn.cumulative_sum(SegmentTime())(solution)


class LateralAcceleration(
    Channel[Data], name="Lateral Acceleration", unit=Unit.G
):
    """Lateral acceleration of the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.lateral_acceleration for node in solution]


class LongitudinalAcceleration(
    Channel[Data], name="Longitudinal Acceleration", unit=Unit.G
):
    """Longitudinal acceleration of the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.longitudinal_acceleration for node in solution]


class ResultantAcceleration(
    Channel[Data], name="Resultant Acceleration", unit=Unit.G
):
    """Resultant acceleration of the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        function = fcn.hypotenuse(
            LongitudinalAcceleration(), LateralAcceleration()
        )
        return function(solution)


class StateOfCharge(
    Channel[Data], name="State of Charge", unit=Unit.PERCENTAGE
):
    """State of charge of the battery."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.transient_variables.soc for node in solution]


class CellTemperature(
    Channel[Data], name="Cell Temperature", unit=Unit.DEGREE_CELSIUS
):
    """Average temperature of the battery cells."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [node.transient_variables.cell_temperature for node in solution]


class AccumulatorCurrent(
    Channel[Data], name="Accumulator Current", unit=Unit.AMPERE
):
    """Average current of the battery cells."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [
            node.calculated_vehicle_state.accumulator_current
            for node in solution
        ]


class HeatingPower(Channel[Data], name="Heating Power", unit=Unit.WATT):
    """Heating power of the accumulator."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [
            node.calculated_vehicle_state.heating_power for node in solution
        ]


class CoolingPower(Channel[Data], name="Cooling Power", unit=Unit.WATT):
    """Cooling power of the accumulator."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [
            node.calculated_vehicle_state.cooling_power for node in solution
        ]


class NetHeatingPower(Channel[Data], name="Net Heating Power", unit=Unit.WATT):
    """Net heating power of the accumulator."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [
            node.calculated_vehicle_state.net_heating_power for node in solution
        ]


class LapNumber(Channel[Data], name="Lap Number"):
    """Current lap number."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return [float(node.lap_number) for node in solution]


class PlotLap(Channel[Lap], name="Lap Number"):
    """Current lap number."""

    def _channel_fcn(self, solution: Solution) -> Lap:
        return list(set([float(node.lap_number) for node in solution]))


def lap_average(channel: fcn.ChannelFcn) -> fcn.ChannelFcn:
    def inner(solution: Solution) -> list[float]:
        lap_solutions = solution.get_lap_solutions()
        return [fcn.average(channel)(s) for s in lap_solutions]

    return inner


def lap_max(channel: fcn.ChannelFcn) -> fcn.ChannelFcn:
    def inner(solution: Solution) -> list[float]:
        lap_solutions = solution.get_lap_solutions()
        return [fcn.maximum(channel)(s) for s in lap_solutions]

    return inner


def lap_total(channel: fcn.ChannelFcn) -> fcn.ChannelFcn:
    def inner(solution: Solution) -> list[float]:
        lap_solutions = solution.get_lap_solutions()
        return [fcn.total(channel)(s) for s in lap_solutions]

    return inner


class LapTime(Channel[Data], name="Lap Time", unit=Unit.SECOND):
    """Lap time of the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return lap_total(SegmentTime())(solution)


class LapAvgVelocity(
    Channel[Data], name="Average Velocity", unit=Unit.KILOMETER_PER_HOUR
):
    """Lap average velocity of the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return lap_average(Velocity())(solution)


class LapMaxVelocity(
    Channel[Data], name="Maximum Velocity", unit=Unit.KILOMETER_PER_HOUR
):
    """Lap max velocity of the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return lap_max(Velocity())(solution)


class LapMaxCurrent(Channel[Data], name="Maximum Current", unit=Unit.AMPERE):
    """Lap max current of the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return lap_max(AccumulatorCurrent())(solution)


class LapAvgCurrent(Channel[Data], name="Average Current", unit=Unit.AMPERE):
    """Lap average current of the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return lap_average(AccumulatorCurrent())(solution)


class LapAvgSOC(Channel[Data], name="State of Charge", unit=Unit.PERCENTAGE):
    """Lap average SOC of the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return lap_average(StateOfCharge())(solution)


class LapAvgTemperature(
    Channel[Data], name="Cell Temperature", unit=Unit.DEGREE_CELSIUS
):
    """Lap average temperature of the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return lap_average(CellTemperature())(solution)


class LapAvgMotorTorque(
    Channel[Data], name="Motor Torque", unit=Unit.NEWTON_METER
):
    """Lap average motor torque of the vehicle."""

    def _channel_fcn(self, solution: Solution) -> Data:
        return lap_average(MotorTorque())(solution)
